version: '3.8'

services:
  chaos-app:
    build: ./Chaos-app
    container_name: chaos-app
    ports:
      - "8000:8000"
    volumes:
      - shared-logs:/var/log/chaos-app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - codeweaver-net

  codeweaver-agent:
    build: ./Core
    container_name: codeweaver-agent
    ports:
      - "8001:8001"
    volumes:
      - shared-logs:/logs
      - ./Chaos-app:/workspace:ro
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PROJECT_PATH=/workspace
    depends_on:
      chaos-app:
        condition: service_healthy
    networks:
      - codeweaver-net

  dashboard-next:
    build: ./dashboard-next
    container_name: dashboard-next
    ports:
      - "3000:3000"
    volumes:
      - shared-logs:/logs:ro
    environment:
      - NEXT_PUBLIC_AGENT_URL=http://localhost:8001
      - NEXT_PUBLIC_CHAOS_URL=http://localhost:8000
    depends_on:
      - codeweaver-agent
      - chaos-app
    networks:
      - codeweaver-net

volumes:
  shared-logs:


networks:
  codeweaver-net:
    driver: bridge
